services:
  - type: web
    name: ampscout
    env: node
    buildCommand: npm install && npm run build
    startCommand: npm install -g serve && serve -s dist
    envVars:
      - key: NODE_VERSION
        value: 16 